export const FONTS_DATA = [
  {
    id: 'inter',
    name: 'Inter',
    family: "'Inter', sans-serif",
    type: 'Sans-Serif',
    category: 'Corporativo / Tecnológico',
    description: 'Diseñada específicamente para pantallas. Extremadamente limpia, neutra y legible en cualquier tamaño.',
    h1_sample: 'Evolución y Liderazgo Digital',
    h2_sample: 'Plataformas escalables diseñadas para el futuro de los negocios.',
    insta_sample: 'La simplicidad es la máxima sofisticación en el desarrollo web.',
    body_sample: 'Inter es la tipografía preferida por empresas de software y productos digitales. Su excelente espaciado y legibilidad la convierten en la opción perfecta para interfaces y textos extensos.'
  },
  {
    id: 'montserrat',
    name: 'Montserrat',
    family: "'Montserrat', sans-serif",
    type: 'Sans-Serif',
    category: 'Moderno / Geométrico',
    description: 'Inspirada en los antiguos carteles del histórico barrio de Montserrat en Buenos Aires. Llena de fuerza y carácter.',
    h1_sample: 'CREATIVIDAD SIN LÍMITES',
    h2_sample: 'Campañas visuales que capturan la esencia de tu negocio.',
    insta_sample: 'Hazlo simple, pero significativo. El diseño habla por tu marca.',
    body_sample: 'Montserrat destaca por su gran presencia visual, especialmente en sus variantes más gruesas. Es ideal para títulos llamativos y piezas de comunicación en redes sociales.'
  },
  {
    id: 'playfair-display',
    name: 'Playfair Display',
    family: "'Playfair Display', serif",
    type: 'Serif',
    category: 'Elegante / Editorial',
    description: 'Una tipografía clásica con un marcado contraste en sus trazos. Aporta prestigio, elegancia y un tono premium.',
    h1_sample: 'El Arte de la Distinción',
    h2_sample: 'Estética refinada para marcas con legado y visión.',
    insta_sample: 'El lujo no es la ausencia de ruido, sino la presencia de armonía.',
    body_sample: 'Playfair Display es perfecta para marcas de moda, lujo, editoriales y títulos principales (H1) que busquen comunicar autoridad y elegancia clásica.'
  },
  {
    id: 'poppins',
    name: 'Poppins',
    family: "'Poppins', sans-serif",
    type: 'Sans-Serif',
    category: 'Amigable / Moderno',
    description: 'Una sans-serif geométrica con un aire muy amigable gracias a sus formas circulares y su estructura abierta.',
    h1_sample: 'Ideas que conectan personas',
    h2_sample: 'Diseñamos experiencias interactivas que cautivan a tu audiencia.',
    insta_sample: 'Conectar es el primer paso para crear un impacto duradero.',
    body_sample: 'Poppins es increíblemente popular por su tono cercano y accesible. Funciona fantásticamente bien tanto en cabeceras de sitios web corporativos como en posts creativos de Instagram.'
  },
  {
    id: 'syne',
    name: 'Syne',
    family: "'Syne', sans-serif",
    type: 'Sans-Serif',
    category: 'Artístico / Vanguardista',
    description: 'Diseñada originalmente para un centro de arte en Francia. Se vuelve extremadamente ancha y expresiva en pesos altos.',
    h1_sample: 'DISEÑO MÁS ALLÁ DE LO COMÚN',
    h2_sample: 'Marcas audaces que no temen destacar en la multitud.',
    insta_sample: 'Rompe las reglas. Lo convencional nunca hizo historia.',
    body_sample: 'Syne es una de las tipografías en tendencia más potentes del panorama del diseño. En sus pesos más altos adquiere formas únicas perfectas para titulares de Instagram y marcas de diseño independiente.'
  },
  {
    id: 'cormorant-garamond',
    name: 'Cormorant Garamond',
    family: "'Cormorant Garamond', serif",
    type: 'Serif',
    category: 'Lujo / Premium',
    description: 'Una interpretación majestuosa del clásico estilo Garamond. Posee curvas extremadamente delicadas y trazos muy finos.',
    h1_sample: 'Belleza y Alta Costura',
    h2_sample: 'Joyas del diseño contemporáneo fabricadas con maestría.',
    insta_sample: 'Los detalles no son el diseño; los detalles hacen al diseño.',
    body_sample: 'Cormorant Garamond respira sofisticación y delicadeza. Es perfecta para logotipos, invitaciones, marcas de alta gama y textos literarios refinados.'
  },
  {
    id: 'bebas-neue',
    name: 'Bebas Neue',
    family: "'Bebas Neue', sans-serif",
    type: 'Sans-Serif',
    category: 'Impacto / Poster',
    description: 'Tipografía de condensación estrecha y solo mayúsculas. Ideal para gritar mensajes importantes con fuerza y estilo.',
    h1_sample: 'LLEGÓ EL MOMENTO DE ACTUAR',
    h2_sample: 'ESTRATEGIAS DIRECTAS QUE MAXIMIZAN RESULTADOS.',
    insta_sample: 'MENOS REGLAS. MÁS ACCIÓN. CREA SIN MIEDO.',
    body_sample: 'Bebas Neue es la reina indiscutible de las miniaturas de video, carteles publicitarios y cabeceras de Instagram donde la inmediatez y la fuerza del mensaje son la máxima prioridad.'
  },
  {
    id: 'plus-jakarta-sans',
    name: 'Plus Jakarta Sans',
    family: "'Plus Jakarta Sans', sans-serif",
    type: 'Sans-Serif',
    category: 'Corporativo Moderno',
    description: 'Una tipografía limpia con proporciones muy equilibradas y pequeños toques geométricos que le dan frescura y distinción.',
    h1_sample: 'Soluciones Inteligentes para tu Empresa',
    h2_sample: 'Optimizamos procesos globales con diseño centrado en el usuario.',
    insta_sample: 'El buen diseño es invisible; solo notas cuando no está.',
    body_sample: 'Plus Jakarta Sans ofrece un aspecto corporativo muy pulido pero moderno. Ideal para SaaS, startups tecnológicas y consultorías que buscan una imagen profesional e innovadora.'
  },
  {
    id: 'cinzel',
    name: 'Cinzel',
    family: "'Cinzel', serif",
    type: 'Serif',
    category: 'Clásico / Monumental',
    description: 'Inspirada en las inscripciones de monumentos romanos antiguos. Transmite historia, estatus y una gran solidez clásica.',
    h1_sample: 'VALOR QUE PERDURA EN EL TIEMPO',
    h2_sample: 'Arquitectura y branding de alto nivel institucional.',
    insta_sample: 'Construimos sobre cimientos de excelencia y legado histórico.',
    body_sample: 'Cinzel evoca la sobriedad y grandiosidad del arte clásico. Es idónea para firmas legales, marcas de alta joyería, museos e instituciones con un fuerte sentido del prestigio.'
  },
  {
    id: 'merriweather',
    name: 'Merriweather',
    family: "'Merriweather', serif",
    type: 'Serif',
    category: 'Editorial / Robusto',
    description: 'Diseñada para ser leída de manera óptima en pantallas. Sus formas son robustas, de altura alta y trazos muy estables.',
    h1_sample: 'Perspectivas en el Periodismo Global',
    h2_sample: 'Crónicas y análisis en profundidad con el máximo confort de lectura.',
    insta_sample: 'El conocimiento comienza al pasar la primera página de un libro.',
    body_sample: 'Merriweather es una tipografía serif extraordinariamente agradable para la lectura prolongada en pantallas. Muy utilizada por periódicos digitales, blogs literarios y revistas en línea.'
  },
  {
    id: 'raleway',
    name: 'Raleway',
    family: "'Raleway', sans-serif",
    type: 'Sans-Serif',
    category: 'Elegante / Minimalista',
    description: 'Una tipografía sans-serif que destaca por su elegancia y detalles peculiares (como la "W" cruzada). Posee pesos ultra-delgados increíbles.',
    h1_sample: 'El Futuro de la Simplicidad',
    h2_sample: 'Diseño arquitectónico y proyectos residenciales premium.',
    insta_sample: 'La elegancia no consiste en llamar la atención, sino en ser recordado.',
    body_sample: 'Raleway destaca en proyectos de branding minimalista. Sus variantes más delgadas (thin, light) aportan una delicadeza única a los encabezados, mientras que sus pesos medios ofrecen gran legibilidad.'
  },
  {
    id: 'lora',
    name: 'Lora',
    family: "'Lora', serif",
    type: 'Serif',
    category: 'Cercano / Editorial',
    description: 'Una serif contemporánea con raíces caligráficas. Sus curvas suaves transmiten calidez, sinceridad y sobriedad intelectual.',
    h1_sample: 'Reflexiones sobre Diseño Humano',
    h2_sample: 'Buscamos la armonía entre el espacio urbano y las personas.',
    insta_sample: 'Escribir bien es pensar bien. Diseñar bien es hacer sentir.',
    body_sample: 'Lora combina a la perfección la formalidad de una serif con pinceladas suaves que la hacen muy humana y cercana. Excelente tanto para títulos como para bloques de texto extensos.'
  },
  {
    id: 'oswald',
    name: 'Oswald',
    family: "'Oswald', sans-serif",
    type: 'Sans-Serif',
    category: 'Condensado / Editorial',
    description: 'Una tipografía condensada que reinterpreta el estilo clásico de la Alternate Gothic. Dinámica, compacta y muy estructurada.',
    h1_sample: 'RESULTADOS CON IMPACTO DIRECTO',
    h2_sample: 'REVOLUCIONANDO EL ACCESO A LA INFORMACIÓN DIGITAL.',
    insta_sample: 'SÉ RÁPIDO. SÉ DIRECTO. HAZ QUE CADA DETALLE COUNTE.',
    body_sample: 'Oswald is fantástica para portadas de noticias, secciones informativas densas y titulares donde el espacio horizontal está optimizado pero se requiere un impacto rotundo.'
  },
  {
    id: 'dm-sans',
    name: 'DM Sans',
    family: "'DM Sans', sans-serif",
    type: 'Sans-Serif',
    category: 'Corporativo / Neutro',
    description: 'Una tipografía geométrica diseñada para ser legible en pantallas pequeñas. Su sencillez es su mayor virtud.',
    h1_sample: 'Innovación que simplifica tu día',
    h2_sample: 'Infraestructura robusta para soluciones integrales y seguras.',
    insta_sample: 'El minimalismo no es la ausencia de cosas, sino la cantidad exacta.',
    body_sample: 'DM Sans ofrece un tono neutral e institucional muy confiable. Al carecer de excentricidades, se adapta camaleónicamente a cualquier proyecto y permite que el contenido sea el protagonista.'
  },
  // NUEVAS TIPOGRAFÍAS AGREGADAS (HASTA COMPLETAR 30)
  {
    id: 'outfit',
    name: 'Outfit',
    family: "'Outfit', sans-serif",
    type: 'Sans-Serif',
    category: 'Moderno / Geométrico',
    description: 'Una tipografía sans-serif geométrica extremadamente limpia y equilibrada. Perfecta para dar una imagen de modernidad absoluta.',
    h1_sample: 'Diseño Centrado en el Futuro',
    h2_sample: 'Creamos interfaces intuitivas que transforman negocios.',
    insta_sample: 'La claridad en la marca es el camino más rápido hacia la confianza.',
    body_sample: 'Outfit fue diseñada para marcas de consumo masivo y productos digitales modernos. Su consistencia geométrica y sus pesos delgados dan una apariencia sofisticada.'
  },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    family: "'Space Grotesk', sans-serif",
    type: 'Sans-Serif',
    category: 'Tecnológico / Futurista',
    description: 'Una grotesca con detalles mecánicos y geométricos muy marcados. Es la favorita de startups tecnológicas y proyectos de blockchain.',
    h1_sample: 'SISTEMAS DESCENTRALIZADOS',
    h2_sample: 'Explorando nuevos paradigmas en la infraestructura web.',
    insta_sample: 'El futuro del software se construye sobre arquitectura abierta.',
    body_sample: 'Space Grotesk ofrece un carácter único que la diferencia de las sans-serif corporativas convencionales. Sus trazos angulares le otorgan un tono robótico, moderno e innovador.'
  },
  {
    id: 'fraunces',
    name: 'Fraunces',
    family: "'Fraunces', serif",
    type: 'Serif',
    category: 'Expresivo / Vintage',
    description: 'Una tipografía serif con un estilo "soft-serif" muy marcado, inspirada en las tipografías tipográficas de principios del siglo XX.',
    h1_sample: 'Dulce Nostalgia Visual',
    h2_sample: 'Branding con raíces orgánicas y un espíritu libre.',
    insta_sample: 'Hazlo con pasión o no lo hagas. El arte reside en la entrega.',
    body_sample: 'Fraunces destaca por sus terminales voluptuosos y sus variaciones de eje. Es perfecta para empaques de productos artesanales, revistas independientes y marcas con enfoque humano.'
  },
  {
    id: 'urbanist',
    name: 'Urbanist',
    family: "'Urbanist', sans-serif",
    type: 'Sans-Serif',
    category: 'Estilo de Vida / Premium',
    description: 'Una sans-serif geométrica diseñada con un enfoque en la neutralidad estética y el balance espacial.',
    h1_sample: 'Estética Urbana y Funcional',
    h2_sample: 'Arquitectura interior que redefine la comodidad.',
    insta_sample: 'Menos es más cuando cada elemento tiene un propósito claro.',
    body_sample: 'Urbanist es ideal para marcas de moda minimalista, estudios de diseño de interiores, portafolios de fotografía y cualquier proyecto que busque una presencia pulida sin esfuerzo.'
  },
  {
    id: 'bricolage-grotesque',
    name: 'Bricolage Grotesque',
    family: "'Bricolage Grotesque', sans-serif",
    type: 'Sans-Serif',
    category: 'Artístico / Excéntrico',
    description: 'Una mezcla de fuentes antiguas francesas y tipografías británicas de posters. Llena de curvas expresivas y giros divertidos.',
    h1_sample: 'CREATIVIDAD INDÓMITA',
    h2_sample: 'Campañas publicitarias que se salen del guión preestablecido.',
    insta_sample: 'Si todos van a la derecha, explora qué hay en la izquierda.',
    body_sample: 'Bricolage Grotesque es una fuente de display cargada de excentricidad. En textos largos tiene un tono rústico e interesante, pero en cabeceras de Instagram y logos es un imán de atención.'
  },
  {
    id: 'instrument-serif',
    name: 'Instrument Serif',
    family: "'Instrument Serif', serif",
    type: 'Serif',
    category: 'Elegancia Editorial',
    description: 'Una tipografía de display serif de gran altura, estrecha y de marcado contraste fino. Altamente sofisticada.',
    h1_sample: 'El Silencio de la Elegancia',
    h2_sample: 'Alta sastrería y mobiliario de edición limitada.',
    insta_sample: 'El estilo no es algo que se compra; es la firma de tu alma.',
    body_sample: 'Instrument Serif se inspira en las tipografías tradicionales para periódicos, pero adaptada con un perfil mucho más estilizado y refinado. Ideal para encabezados de lujo e identidades premium.'
  },
  {
    id: 'young-serif',
    name: 'Young Serif',
    family: "'Young Serif', serif",
    type: 'Serif',
    category: 'Retro / Amigable',
    description: 'Una serif pesada de peso único, inspirada en las formas redondeadas del branding retro de los años 70.',
    h1_sample: 'Comida Real con Amor',
    h2_sample: 'Recetas familiares y productos de la tierra directos a tu hogar.',
    insta_sample: 'La cocina es el corazón de la casa, donde se hornean los recuerdos.',
    body_sample: 'Young Serif aporta calidez, amigabilidad y un toque nostálgico. Al tener un único peso grueso, es fantástica para logotipos directos y textos cortos con una gran dosis de amabilidad.'
  },
  {
    id: 'sora',
    name: 'Sora',
    family: "'Sora', sans-serif",
    type: 'Sans-Serif',
    category: 'Tech / Minimalista',
    description: 'Diseñada originalmente para aplicaciones fintech. Tiene una estructura robusta y un espaciado generoso.',
    h1_sample: 'Finanzas Inteligentes y Transparentes',
    h2_sample: 'Tu capital seguro con tecnología de encriptación de última generación.',
    insta_sample: 'La simplicidad en la experiencia de usuario es el mejor servicio.',
    body_sample: 'Sora destaca por su gran legibilidad en tamaños pequeños. Su carácter técnico y moderno la convierte en una opción segura para startups fintech, SaaS y aplicaciones móviles.'
  },
  {
    id: 'jost',
    name: 'Jost',
    family: "'Jost', sans-serif",
    type: 'Sans-Serif',
    category: 'Moderno / Futura',
    description: 'Inspirada en el clásico diseño geométrico alemán de los años 1920 (como Futura). Altamente funcional y atemporal.',
    h1_sample: 'Diseño para las Próximas Generaciones',
    h2_sample: 'Proyectos sostenibles y mobiliario de diseño ecológico.',
    insta_sample: 'La buena forma sigue a la función, pero la gran forma deleita al espíritu.',
    body_sample: 'Jost es una alternativa digital premium a Futura. Es limpia, equilibrada, y sus proporciones geométricas aportan un aire institucional, pulcro e industrial.'
  },
  {
    id: 'libre-baskerville',
    name: 'Libre Baskerville',
    family: "'Libre Baskerville', serif",
    type: 'Serif',
    category: 'Clásico / Académico',
    description: 'Una serif optimizada para pantallas basada en la clásica Baskerville del siglo XVIII. Autoridad e historia.',
    h1_sample: 'Ensayos sobre la Cultura y el Arte',
    h2_sample: 'Publicaciones académicas y análisis filosóficos contemporáneos.',
    insta_sample: 'La lectura nos regala ojos para ver mundos que otros solo imaginan.',
    body_sample: 'Libre Baskerville es sumamente legible y respetable. Se utiliza comúnmente para marcas institucionales, editoriales tradicionales, bufetes de abogados y blogs de texto largo.'
  },
  {
    id: 'spectral',
    name: 'Spectral',
    family: "'Spectral', serif",
    type: 'Serif',
    category: 'Editorial / Pantallas',
    description: 'Una tipografía serif diseñada expresamente para una lectura fluida en entornos web y de documentos digitales densos.',
    h1_sample: 'Informes de Economía y Geopolítica',
    h2_sample: 'Análisis geopolítico global y estudios de mercado trimestrales.',
    insta_sample: 'El verdadero análisis no simplifica los hechos; ilumina la complejidad.',
    body_sample: 'Spectral es una serif de excelente rendimiento. Su estructura ligera y sus itálicas elegantes la hacen ideal para sitios de noticias premium, blogs técnicos y libros interactivos.'
  },
  {
    id: 'tenor-sans',
    name: 'Tenor Sans',
    family: "'Tenor Sans', sans-serif",
    type: 'Sans-Serif',
    category: 'Elegancia Femenina',
    description: 'Una sans-serif humanista con un toque muy elegante y proporciones estilizadas. Muy usada en moda y cosmética.',
    h1_sample: 'Armonía y Cuidado de la Piel',
    h2_sample: 'Tratamientos botánicos que nutren tu belleza natural.',
    insta_sample: 'El autocuidado no es un lujo; es el respeto por tu propio templo.',
    body_sample: 'Tenor Sans ofrece una calidez y sofisticación sutiles en sus formas que evocan las tipografías romanas de alta costura, pero con la limpieza del sans-serif.'
  },
  {
    id: 'volkhov',
    name: 'Volkhov',
    family: "'Volkhov', serif",
    type: 'Serif',
    category: 'Editorial / Robusta',
    description: 'Una serif robusta de gran altura con contrastes moderados. Muestra gran estabilidad y una presencia asertiva.',
    h1_sample: 'Crónicas de Viajes e Historia',
    h2_sample: 'Explorando los rincones más antiguos del continente europeo.',
    insta_sample: 'Viajar es descubrir que todos están equivocados sobre otros países.',
    body_sample: 'Volkhov funciona fantásticamente como una tipografía editorial con personalidad. Sus detalles asimétricos sutiles la hacen atractiva en títulos, y su robustez la hace muy legible en párrafos.'
  },
  {
    id: 'prata',
    name: 'Prata',
    family: "'Prata', serif",
    type: 'Serif',
    category: 'Lujo / Didone',
    description: 'Una serif de estilo Didone elegante con un contraste extremo entre trazos finos y gruesos, rematada con formas en lágrima.',
    h1_sample: 'Colecciones de Alta Joyería',
    h2_sample: 'Brillo eterno esculpido con metales preciosos.',
    insta_sample: 'La elegancia es la única belleza que nunca se marchita.',
    body_sample: 'Prata es una tipografía clásica de lujo. Sus detalles Didone la hacen brillar en tamaños grandes (H1), dando un estatus premium instantáneo a cualquier marca de moda o joyería.'
  },
  {
    id: 'abril-fatface',
    name: 'Abril Fatface',
    family: "'Abril Fatface', serif",
    type: 'Serif',
    category: 'Display / Posters',
    description: 'Inspirada en las tipografías publicitarias gruesas del siglo XIX en Inglaterra. Audaz, dramática y clásica.',
    h1_sample: '¡GRAN EVENTO ANUAL DE DISEÑO!',
    h2_sample: 'CONFERENCIAS EXCLUSIVAS CON MENTORES GLOBALES.',
    insta_sample: 'HAZLO CON DRAMATISMO O NO LO INTENTES.',
    body_sample: 'Abril Fatface es una de las fuentes serif de display más dramáticas. Su peso ultra-grueso y sus itálicas estilizadas la convierten en la favorita para marcas que desean gritar sofisticación.'
  },
  {
    id: 'manrope',
    name: 'Manrope',
    family: "'Manrope', sans-serif",
    type: 'Sans-Serif',
    category: 'Corporativo / Versátil',
    description: 'Una sans-serif geométrica moderna y sumamente equilibrada. Es una de las fuentes más descargadas en el sector corporativo actual.',
    h1_sample: 'Soluciones Globales de Consultoría',
    h2_sample: 'Optimizamos la rentabilidad y cultura de tu organización.',
    insta_sample: 'El éxito colectivo es la suma de pequeños esfuerzos diarios.',
    body_sample: 'Manrope es considerada la navaja suiza de las tipografías corporativas. Se adapta impecablemente a interfaces de usuario, textos informativos complejos y logotipos minimalistas.'
  }
];
