export const FONTS_DATA = [
  {
    id: 'inter',
    name: 'Inter',
    family: "'Inter', sans-serif",
    type: 'Sans-Serif',
    category: 'Corporativo / Tecnológico',
    description: 'Diseñada específicamente para pantallas. Extremadamente limpia, neutra y legible en cualquier tamaño.',
    h1_sample: 'Evolución y Liderazgo Digital',
    h2_sample: 'Plataformas escalables diseñadas para el futuro de los negocios.',
    insta_sample: 'La simplicidad es la máxima sofisticación en el desarrollo web.',
    body_sample: 'Inter es la tipografía preferida por empresas de software y productos digitales. Su excelente espaciado y legibilidad la convierten en la opción perfecta para interfaces y textos extensos.'
  },
  {
    id: 'montserrat',
    name: 'Montserrat',
    family: "'Montserrat', sans-serif",
    type: 'Sans-Serif',
    category: 'Moderno / Geométrico',
    description: 'Inspirada en los antiguos carteles del histórico barrio de Montserrat en Buenos Aires. Llena de fuerza y carácter.',
    h1_sample: 'CREATIVIDAD SIN LÍMITES',
    h2_sample: 'Campañas visuales que capturan la esencia de tu negocio.',
    insta_sample: 'Hazlo simple, pero significativo. El diseño habla por tu marca.',
    body_sample: 'Montserrat destaca por su gran presencia visual, especialmente en sus variantes más gruesas. Es ideal para títulos llamativos y piezas de comunicación en redes sociales.'
  },
  {
    id: 'playfair-display',
    name: 'Playfair Display',
    family: "'Playfair Display', serif",
    type: 'Serif',
    category: 'Elegante / Editorial',
    description: 'Una tipografía clásica con un marcado contraste en sus trazos. Aporta prestigio, elegancia y un tono premium.',
    h1_sample: 'El Arte de la Distinción',
    h2_sample: 'Estética refinada para marcas con legado y visión.',
    insta_sample: 'El lujo no es la ausencia de ruido, sino la presencia de armonía.',
    body_sample: 'Playfair Display es perfecta para marcas de moda, lujo, editoriales y títulos principales (H1) que busquen comunicar autoridad y elegancia clásica.'
  },
  {
    id: 'poppins',
    name: 'Poppins',
    family: "'Poppins', sans-serif",
    type: 'Sans-Serif',
    category: 'Amigable / Moderno',
    description: 'Una sans-serif geométrica con un aire muy amigable gracias a sus formas circulares y su estructura abierta.',
    h1_sample: 'Ideas que conectan personas',
    h2_sample: 'Diseñamos experiencias interactivas que cautivan a tu audiencia.',
    insta_sample: 'Conectar es el primer paso para crear un impacto duradero.',
    body_sample: 'Poppins es increíblemente popular por su tono cercano y accesible. Funciona fantásticamente bien tanto en cabeceras de sitios web corporativos como en posts creativos de Instagram.'
  },
  {
    id: 'syne',
    name: 'Syne',
    family: "'Syne', sans-serif",
    type: 'Sans-Serif',
    category: 'Artístico / Vanguardista',
    description: 'Diseñada originalmente para un centro de arte en Francia. Se vuelve extremadamente ancha y expresiva en pesos altos.',
    h1_sample: 'DISEÑO MÁS ALLÁ DE LO COMÚN',
    h2_sample: 'Marcas audaces que no temen destacar en la multitud.',
    insta_sample: 'Rompe las reglas. Lo convencional nunca hizo historia.',
    body_sample: 'Syne es una de las tipografías en tendencia más potentes del panorama del diseño. En sus pesos más altos adquiere formas únicas perfectas para titulares de Instagram y marcas de diseño independiente.'
  },
  {
    id: 'cormorant-garamond',
    name: 'Cormorant Garamond',
    family: "'Cormorant Garamond', serif",
    type: 'Serif',
    category: 'Lujo / Premium',
    description: 'Una interpretación majestuosa del clásico estilo Garamond. Posee curvas extremadamente delicadas y trazos muy finos.',
    h1_sample: 'Belleza y Alta Costura',
    h2_sample: 'Joyas del diseño contemporáneo fabricadas con maestría.',
    insta_sample: 'Los detalles no son el diseño; los detalles hacen al diseño.',
    body_sample: 'Cormorant Garamond respira sofisticación y delicadeza. Es perfecta para logotipos, invitaciones, marcas de alta gama y textos literarios refinados.'
  },
  {
    id: 'bebas-neue',
    name: 'Bebas Neue',
    family: "'Bebas Neue', sans-serif",
    type: 'Sans-Serif',
    category: 'Impacto / Poster',
    description: 'Tipografía de condensación estrecha y solo mayúsculas. Ideal para gritar mensajes importantes con fuerza y estilo.',
    h1_sample: 'LLEGÓ EL MOMENTO DE ACTUAR',
    h2_sample: 'ESTRATEGIAS DIRECTAS QUE MAXIMIZAN RESULTADOS.',
    insta_sample: 'MENOS REGLAS. MÁS ACCIÓN. CREA SIN MIEDO.',
    body_sample: 'Bebas Neue es la reina indiscutible de las miniaturas de video, carteles publicitarios y cabeceras de Instagram donde la inmediatez y la fuerza del mensaje son la máxima prioridad.'
  },
  {
    id: 'plus-jakarta-sans',
    name: 'Plus Jakarta Sans',
    family: "'Plus Jakarta Sans', sans-serif",
    type: 'Sans-Serif',
    category: 'Corporativo Moderno',
    description: 'Una tipografía limpia con proporciones muy equilibradas y pequeños toques geométricos que le dan frescura y distinción.',
    h1_sample: 'Soluciones Inteligentes para tu Empresa',
    h2_sample: 'Optimizamos procesos globales con diseño centrado en el usuario.',
    insta_sample: 'El buen diseño es invisible; solo notas cuando no está.',
    body_sample: 'Plus Jakarta Sans ofrece un aspecto corporativo muy pulido pero moderno. Ideal para SaaS, startups tecnológicas y consultorías que buscan una imagen profesional e innovadora.'
  },
  {
    id: 'cinzel',
    name: 'Cinzel',
    family: "'Cinzel', serif",
    type: 'Serif',
    category: 'Clásico / Monumental',
    description: 'Inspirada en las inscripciones de monumentos romanos antiguos. Transmite historia, estatus y una gran solidez clásica.',
    h1_sample: 'VALOR QUE PERDURA EN EL TIEMPO',
    h2_sample: 'Arquitectura y branding de alto nivel institucional.',
    insta_sample: 'Construimos sobre cimientos de excelencia y legado histórico.',
    body_sample: 'Cinzel evoca la sobriedad y grandiosidad del arte clásico. Es idónea para firmas legales, marcas de alta joyería, museos e instituciones con un fuerte sentido del prestigio.'
  },
  {
    id: 'merriweather',
    name: 'Merriweather',
    family: "'Merriweather', serif",
    type: 'Serif',
    category: 'Editorial / Robusto',
    description: 'Diseñada para ser leída de manera óptima en pantallas. Sus formas son robustas, de altura alta y trazos muy estables.',
    h1_sample: 'Perspectivas en el Periodismo Global',
    h2_sample: 'Crónicas y análisis en profundidad con el máximo confort de lectura.',
    insta_sample: 'El conocimiento comienza al pasar la primera página de un libro.',
    body_sample: 'Merriweather es una tipografía serif extraordinariamente agradable para la lectura prolongada en pantallas. Muy utilizada por periódicos digitales, blogs literarios y revistas en línea.'
  },
  {
    id: 'raleway',
    name: 'Raleway',
    family: "'Raleway', sans-serif",
    type: 'Sans-Serif',
    category: 'Elegante / Minimalista',
    description: 'Una tipografía sans-serif que destaca por su elegancia y detalles peculiares (como la "W" cruzada). Posee pesos ultra-delgados increíbles.',
    h1_sample: 'El Futuro de la Simplicidad',
    h2_sample: 'Diseño arquitectónico y proyectos residenciales premium.',
    insta_sample: 'La elegancia no consiste en llamar la atención, sino en ser recordado.',
    body_sample: 'Raleway destaca en proyectos de branding minimalista. Sus variantes más delgadas (thin, light) aportan una delicadeza única a los encabezados, mientras que sus pesos medios ofrecen gran legibilidad.'
  },
  {
    id: 'lora',
    name: 'Lora',
    family: "'Lora', serif",
    type: 'Serif',
    category: 'Cercano / Editorial',
    description: 'Una serif contemporánea con raíces caligráficas. Sus curvas suaves transmiten calidez, sinceridad y sobriedad intelectual.',
    h1_sample: 'Reflexiones sobre Diseño Humano',
    h2_sample: 'Buscamos la armonía entre el espacio urbano y las personas.',
    insta_sample: 'Escribir bien es pensar bien. Diseñar bien es hacer sentir.',
    body_sample: 'Lora combina a la perfección la formalidad de una serif con pinceladas suaves que la hacen muy humana y cercana. Excelente tanto para títulos como para bloques de texto extensos.'
  },
  {
    id: 'oswald',
    name: 'Oswald',
    family: "'Oswald', sans-serif",
    type: 'Sans-Serif',
    category: 'Condensado / Editorial',
    description: 'Una tipografía condensada que reinterpreta el estilo clásico de la Alternate Gothic. Dinámica, compacta y muy estructurada.',
    h1_sample: 'RESULTADOS CON IMPACTO DIRECTO',
    h2_sample: 'REVOLUCIONANDO EL ACCESO A LA INFORMACIÓN DIGITAL.',
    insta_sample: 'SÉ RÁPIDO. SÉ DIRECTO. HAZ QUE CADA DETALLE CUENTE.',
    body_sample: 'Oswald es fantástica para portadas de noticias, secciones informativas densas y titulares donde el espacio horizontal está optimizado pero se requiere un impacto rotundo.'
  },
  {
    id: 'dm-sans',
    name: 'DM Sans',
    family: "'DM Sans', sans-serif",
    type: 'Sans-Serif',
    category: 'Corporativo / Neutro',
    description: 'Una tipografía geométrica diseñada para ser legible en pantallas pequeñas. Su sencillez es su mayor virtud.',
    h1_sample: 'Innovación que simplifica tu día',
    h2_sample: 'Infraestructura robusta para soluciones integrales y seguras.',
    insta_sample: 'El minimalismo no es la ausencia de cosas, sino la cantidad exacta.',
    body_sample: 'DM Sans ofrece un tono neutral e institucional muy confiable. Al carecer de excentricidades, se adapta camaleónicamente a cualquier proyecto y permite que el contenido sea el protagonista.'
  }
];
